export const CATEGORIES: Record<string, string[]> = {
  "Food & Beverages": [
    "Grains & Rice",
    "Snacks",
    "Drinks",
    "Frozen Foods",
    "Dairy Products",
    "Meat & Fish",
    "Spices & Seasoning",
    "Canned & Packaged Goods",
    "Bakery Items",
    "Produce",
  ],
  "Beauty & Personal Care": [
    "Hair Products",
    "Skin Care",
    "Makeup",
    "Fragrances",
    "Body Care",
    "Grooming",
    "Hair Tools & Accessories",
  ],
  "Health & Wellness": [
    "Supplements",
    "Vitamins",
    "Medical Supplies",
    "First Aid",
    "Personal Hygiene",
    "Fitness Nutrition",
  ],
  "Clothing & Apparel": [
    "Men's Wear",
    "Women's Wear",
    "Kids Wear",
    "Shoes",
    "Underwear & Sleepwear",
    "Workwear",
  ],
  "Electronics": [
    "Phones & Accessories",
    "Computers & Laptops",
    "Audio Devices",
    "TVs & Displays",
    "Gaming",
    "Smart Devices",
    "Chargers & Cables",
  ],
  "Home & Kitchen": [
    "Cookware",
    "Kitchen Appliances",
    "Home Decor",
    "Furniture",
    "Cleaning Supplies",
    "Storage & Organization",
    "Bedding",
  ],
  "Office & Stationery": [
    "Notebooks",
    "Pens & Writing Tools",
    "Printing Supplies",
    "Office Equipment",
    "School Supplies",
  ],
  "Baby & Kids": [
    "Baby Food",
    "Diapers & Wipes",
    "Toys",
    "Clothing",
    "Baby Care",
    "School Items",
  ],
  "Agriculture & Farming": [
    "Seeds",
    "Fertilizers",
    "Equipment",
    "Animal Feed",
    "Pesticides",
  ],
  "Tools & Hardware": [
    "Hand Tools",
    "Power Tools",
    "Building Materials",
    "Electrical Supplies",
    "Plumbing Supplies",
  ],
  "Industrial & Bulk Supplies": [
    "Packaging Materials",
    "Wholesale Goods",
    "Raw Materials",
  ],
  "General / Other": [],
};

export const CATEGORY_NAMES = Object.keys(CATEGORIES);
