// Pure data module for country / state selectors.
// No imports. Reference data — keep names and currencies stable.
//
// Currency rules:
//   - The app bills in NGN / GHS / USD / GBP / KES / ZAR / UGX / CAD / EUR today.
//   - USD is the safe global default; unsupported local currencies are NOT used
//     here because they would break billing.
//   - Canada → CAD and the 20 Eurozone members → EUR (real billing currencies with
//     price tables). Mirrors the server-side CountryLookup.BillingCurrencyFor map.
//   - The preserved names/currencies below already exist in the app (businesses
//     store the country name string), so do not rename or re-map them.

export const COUNTRIES: Record<string, { currency: string }> = {
  // --- Preserved (existing app data — do not change) ---
  Nigeria: { currency: "NGN" },
  Ghana: { currency: "GHS" },
  Kenya: { currency: "KES" },
  "South Africa": { currency: "ZAR" },
  Tanzania: { currency: "TZS" },
  Uganda: { currency: "UGX" },
  Rwanda: { currency: "RWF" },
  Cameroon: { currency: "XAF" },
  Senegal: { currency: "XOF" },
  "Ivory Coast": { currency: "XOF" },
  Egypt: { currency: "EGP" },
  Ethiopia: { currency: "ETB" },
  "DR Congo": { currency: "CDF" },
  Angola: { currency: "AOA" },
  Mozambique: { currency: "MZN" },
  Zambia: { currency: "ZMW" },
  Zimbabwe: { currency: "USD" },
  Botswana: { currency: "BWP" },
  Namibia: { currency: "NAD" },
  Malawi: { currency: "MWK" },
  Benin: { currency: "XOF" },
  Togo: { currency: "XOF" },
  "Sierra Leone": { currency: "SLE" },
  Liberia: { currency: "LRD" },
  Gambia: { currency: "GMD" },

  // --- Explicit ---
  "United Kingdom": { currency: "GBP" },
  "United States": { currency: "USD" },

  // --- Everything else = USD ---
  Afghanistan: { currency: "USD" },
  Albania: { currency: "USD" },
  Algeria: { currency: "USD" },
  Andorra: { currency: "USD" },
  "Antigua and Barbuda": { currency: "USD" },
  Argentina: { currency: "USD" },
  Armenia: { currency: "USD" },
  Australia: { currency: "USD" },
  Austria: { currency: "EUR" },
  Azerbaijan: { currency: "USD" },
  Bahamas: { currency: "USD" },
  Bahrain: { currency: "USD" },
  Bangladesh: { currency: "USD" },
  Barbados: { currency: "USD" },
  Belarus: { currency: "USD" },
  Belgium: { currency: "EUR" },
  Belize: { currency: "USD" },
  Bhutan: { currency: "USD" },
  Bolivia: { currency: "USD" },
  "Bosnia and Herzegovina": { currency: "USD" },
  Brazil: { currency: "USD" },
  Brunei: { currency: "USD" },
  Bulgaria: { currency: "USD" },
  "Burkina Faso": { currency: "USD" },
  Burundi: { currency: "USD" },
  "Cabo Verde": { currency: "USD" },
  Cambodia: { currency: "USD" },
  Canada: { currency: "CAD" },
  "Central African Republic": { currency: "USD" },
  Chad: { currency: "USD" },
  Chile: { currency: "USD" },
  China: { currency: "USD" },
  Colombia: { currency: "USD" },
  Comoros: { currency: "USD" },
  Congo: { currency: "USD" },
  "Costa Rica": { currency: "USD" },
  Croatia: { currency: "EUR" },
  Cuba: { currency: "USD" },
  Cyprus: { currency: "EUR" },
  Czechia: { currency: "USD" },
  Denmark: { currency: "USD" },
  Djibouti: { currency: "USD" },
  Dominica: { currency: "USD" },
  "Dominican Republic": { currency: "USD" },
  Ecuador: { currency: "USD" },
  "El Salvador": { currency: "USD" },
  "Equatorial Guinea": { currency: "USD" },
  Eritrea: { currency: "USD" },
  Estonia: { currency: "EUR" },
  Eswatini: { currency: "USD" },
  Fiji: { currency: "USD" },
  Finland: { currency: "EUR" },
  France: { currency: "EUR" },
  Gabon: { currency: "USD" },
  Georgia: { currency: "USD" },
  Germany: { currency: "EUR" },
  Greece: { currency: "EUR" },
  Grenada: { currency: "USD" },
  Guatemala: { currency: "USD" },
  Guinea: { currency: "USD" },
  "Guinea-Bissau": { currency: "USD" },
  Guyana: { currency: "USD" },
  Haiti: { currency: "USD" },
  Honduras: { currency: "USD" },
  "Hong Kong": { currency: "USD" },
  Hungary: { currency: "USD" },
  Iceland: { currency: "USD" },
  India: { currency: "USD" },
  Indonesia: { currency: "USD" },
  Iran: { currency: "USD" },
  Iraq: { currency: "USD" },
  Ireland: { currency: "EUR" },
  Israel: { currency: "USD" },
  Italy: { currency: "EUR" },
  Jamaica: { currency: "USD" },
  Japan: { currency: "USD" },
  Jordan: { currency: "USD" },
  Kazakhstan: { currency: "USD" },
  Kiribati: { currency: "USD" },
  Kosovo: { currency: "USD" },
  Kuwait: { currency: "USD" },
  Kyrgyzstan: { currency: "USD" },
  Laos: { currency: "USD" },
  Latvia: { currency: "EUR" },
  Lebanon: { currency: "USD" },
  Lesotho: { currency: "USD" },
  Libya: { currency: "USD" },
  Liechtenstein: { currency: "USD" },
  Lithuania: { currency: "EUR" },
  Luxembourg: { currency: "EUR" },
  Madagascar: { currency: "USD" },
  Malaysia: { currency: "USD" },
  Maldives: { currency: "USD" },
  Mali: { currency: "USD" },
  Malta: { currency: "EUR" },
  "Marshall Islands": { currency: "USD" },
  Mauritania: { currency: "USD" },
  Mauritius: { currency: "USD" },
  Mexico: { currency: "USD" },
  Micronesia: { currency: "USD" },
  Moldova: { currency: "USD" },
  Monaco: { currency: "USD" },
  Mongolia: { currency: "USD" },
  Montenegro: { currency: "USD" },
  Morocco: { currency: "USD" },
  Myanmar: { currency: "USD" },
  Nauru: { currency: "USD" },
  Nepal: { currency: "USD" },
  Netherlands: { currency: "EUR" },
  "New Zealand": { currency: "USD" },
  Nicaragua: { currency: "USD" },
  Niger: { currency: "USD" },
  "North Korea": { currency: "USD" },
  "North Macedonia": { currency: "USD" },
  Norway: { currency: "USD" },
  Oman: { currency: "USD" },
  Pakistan: { currency: "USD" },
  Palau: { currency: "USD" },
  Palestine: { currency: "USD" },
  Panama: { currency: "USD" },
  "Papua New Guinea": { currency: "USD" },
  Paraguay: { currency: "USD" },
  Peru: { currency: "USD" },
  Philippines: { currency: "USD" },
  Poland: { currency: "USD" },
  Portugal: { currency: "EUR" },
  Qatar: { currency: "USD" },
  Romania: { currency: "USD" },
  Russia: { currency: "USD" },
  "Saint Kitts and Nevis": { currency: "USD" },
  "Saint Lucia": { currency: "USD" },
  "Saint Vincent and the Grenadines": { currency: "USD" },
  Samoa: { currency: "USD" },
  "San Marino": { currency: "USD" },
  "Sao Tome and Principe": { currency: "USD" },
  "Saudi Arabia": { currency: "USD" },
  Serbia: { currency: "USD" },
  Seychelles: { currency: "USD" },
  Singapore: { currency: "USD" },
  Slovakia: { currency: "EUR" },
  Slovenia: { currency: "EUR" },
  "Solomon Islands": { currency: "USD" },
  Somalia: { currency: "USD" },
  "South Korea": { currency: "USD" },
  "South Sudan": { currency: "USD" },
  Spain: { currency: "EUR" },
  "Sri Lanka": { currency: "USD" },
  Sudan: { currency: "USD" },
  Suriname: { currency: "USD" },
  Sweden: { currency: "USD" },
  Switzerland: { currency: "USD" },
  Syria: { currency: "USD" },
  Taiwan: { currency: "USD" },
  Tajikistan: { currency: "USD" },
  Thailand: { currency: "USD" },
  "Timor-Leste": { currency: "USD" },
  Tonga: { currency: "USD" },
  "Trinidad and Tobago": { currency: "USD" },
  Tunisia: { currency: "USD" },
  Turkey: { currency: "USD" },
  Turkmenistan: { currency: "USD" },
  Tuvalu: { currency: "USD" },
  Ukraine: { currency: "USD" },
  "United Arab Emirates": { currency: "USD" },
  Uruguay: { currency: "USD" },
  Uzbekistan: { currency: "USD" },
  Vanuatu: { currency: "USD" },
  "Vatican City": { currency: "USD" },
  Venezuela: { currency: "USD" },
  Vietnam: { currency: "USD" },
  Yemen: { currency: "USD" },
};

export const COUNTRY_NAMES: string[] = Object.keys(COUNTRIES).sort();

export const SUBDIVISIONS: Record<string, { label: string; items: string[] }> = {
  "United States": {
    label: "State",
    items: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "District of Columbia",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
    ],
  },
  Canada: {
    label: "Province / Territory",
    items: [
      "Alberta",
      "British Columbia",
      "Manitoba",
      "New Brunswick",
      "Newfoundland and Labrador",
      "Northwest Territories",
      "Nova Scotia",
      "Nunavut",
      "Ontario",
      "Prince Edward Island",
      "Quebec",
      "Saskatchewan",
      "Yukon",
    ],
  },
  "United Kingdom": {
    label: "Nation",
    items: ["England", "Northern Ireland", "Scotland", "Wales"],
  },
  Australia: {
    label: "State / Territory",
    items: [
      "Australian Capital Territory",
      "New South Wales",
      "Northern Territory",
      "Queensland",
      "South Australia",
      "Tasmania",
      "Victoria",
      "Western Australia",
    ],
  },
  India: {
    label: "State / UT",
    items: [
      "Andaman and Nicobar Islands",
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chandigarh",
      "Chhattisgarh",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Delhi",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jammu and Kashmir",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Ladakh",
      "Lakshadweep",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Puducherry",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
    ],
  },
  Nigeria: {
    label: "State",
    items: [
      "Abia",
      "Adamawa",
      "Akwa Ibom",
      "Anambra",
      "Bauchi",
      "Bayelsa",
      "Benue",
      "Borno",
      "Cross River",
      "Delta",
      "Ebonyi",
      "Edo",
      "Ekiti",
      "Enugu",
      "Federal Capital Territory",
      "Gombe",
      "Imo",
      "Jigawa",
      "Kaduna",
      "Kano",
      "Katsina",
      "Kebbi",
      "Kogi",
      "Kwara",
      "Lagos",
      "Nasarawa",
      "Niger",
      "Ogun",
      "Ondo",
      "Osun",
      "Oyo",
      "Plateau",
      "Rivers",
      "Sokoto",
      "Taraba",
      "Yobe",
      "Zamfara",
    ],
  },
  Ghana: {
    label: "Region",
    items: [
      "Ahafo",
      "Ashanti",
      "Bono",
      "Bono East",
      "Central",
      "Eastern",
      "Greater Accra",
      "North East",
      "Northern",
      "Oti",
      "Savannah",
      "Upper East",
      "Upper West",
      "Volta",
      "Western",
      "Western North",
    ],
  },
  Kenya: {
    label: "County",
    items: [
      "Baringo",
      "Bomet",
      "Bungoma",
      "Busia",
      "Elgeyo-Marakwet",
      "Embu",
      "Garissa",
      "Homa Bay",
      "Isiolo",
      "Kajiado",
      "Kakamega",
      "Kericho",
      "Kiambu",
      "Kilifi",
      "Kirinyaga",
      "Kisii",
      "Kisumu",
      "Kitui",
      "Kwale",
      "Laikipia",
      "Lamu",
      "Machakos",
      "Makueni",
      "Mandera",
      "Marsabit",
      "Meru",
      "Migori",
      "Mombasa",
      "Murang'a",
      "Nairobi",
      "Nakuru",
      "Nandi",
      "Narok",
      "Nyamira",
      "Nyandarua",
      "Nyeri",
      "Samburu",
      "Siaya",
      "Taita-Taveta",
      "Tana River",
      "Tharaka-Nithi",
      "Trans Nzoia",
      "Turkana",
      "Uasin Gishu",
      "Vihiga",
      "Wajir",
      "West Pokot",
    ],
  },
  "South Africa": {
    label: "Province",
    items: [
      "Eastern Cape",
      "Free State",
      "Gauteng",
      "KwaZulu-Natal",
      "Limpopo",
      "Mpumalanga",
      "North West",
      "Northern Cape",
      "Western Cape",
    ],
  },
  Uganda: {
    label: "Region",
    items: ["Central", "Eastern", "Northern", "Western"],
  },
  Germany: {
    label: "State",
    items: [
      "Baden-Württemberg",
      "Bavaria",
      "Berlin",
      "Brandenburg",
      "Bremen",
      "Hamburg",
      "Hesse",
      "Lower Saxony",
      "Mecklenburg-Vorpommern",
      "North Rhine-Westphalia",
      "Rhineland-Palatinate",
      "Saarland",
      "Saxony",
      "Saxony-Anhalt",
      "Schleswig-Holstein",
      "Thuringia",
    ],
  },
  France: {
    label: "Region",
    items: [
      "Auvergne-Rhône-Alpes",
      "Bourgogne-Franche-Comté",
      "Brittany",
      "Centre-Val de Loire",
      "Corsica",
      "Grand Est",
      "Hauts-de-France",
      "Île-de-France",
      "Normandy",
      "Nouvelle-Aquitaine",
      "Occitanie",
      "Pays de la Loire",
      "Provence-Alpes-Côte d'Azur",
    ],
  },
  Brazil: {
    label: "State",
    items: [
      "Acre",
      "Alagoas",
      "Amapá",
      "Amazonas",
      "Bahia",
      "Ceará",
      "Espírito Santo",
      "Federal District",
      "Goiás",
      "Maranhão",
      "Mato Grosso",
      "Mato Grosso do Sul",
      "Minas Gerais",
      "Pará",
      "Paraíba",
      "Paraná",
      "Pernambuco",
      "Piauí",
      "Rio de Janeiro",
      "Rio Grande do Norte",
      "Rio Grande do Sul",
      "Rondônia",
      "Roraima",
      "Santa Catarina",
      "São Paulo",
      "Sergipe",
      "Tocantins",
    ],
  },
  Mexico: {
    label: "State",
    items: [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Coahuila",
      "Colima",
      "Durango",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "Mexico City",
      "Michoacán",
      "Morelos",
      "México",
      "Nayarit",
      "Nuevo León",
      "Oaxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz",
      "Yucatán",
      "Zacatecas",
    ],
  },
  Ireland: {
    label: "County",
    items: [
      "Carlow",
      "Cavan",
      "Clare",
      "Cork",
      "Donegal",
      "Dublin",
      "Galway",
      "Kerry",
      "Kildare",
      "Kilkenny",
      "Laois",
      "Leitrim",
      "Limerick",
      "Longford",
      "Louth",
      "Mayo",
      "Meath",
      "Monaghan",
      "Offaly",
      "Roscommon",
      "Sligo",
      "Tipperary",
      "Waterford",
      "Westmeath",
      "Wexford",
      "Wicklow",
    ],
  },
  "New Zealand": {
    label: "Region",
    items: [
      "Auckland",
      "Bay of Plenty",
      "Canterbury",
      "Gisborne",
      "Hawke's Bay",
      "Manawatū-Whanganui",
      "Marlborough",
      "Nelson",
      "Northland",
      "Otago",
      "Southland",
      "Taranaki",
      "Tasman",
      "Waikato",
      "Wellington",
      "West Coast",
    ],
  },
};

export function subdivisionsFor(
  country?: string | null,
): { label: string; items: string[] } | null {
  return country ? (SUBDIVISIONS[country] ?? null) : null;
}
